import { useMemo, useState } from 'react';
import { ArrowUpRight, Check, CircleAlert, Clock3, Download, FileJson, FileSpreadsheet, Pause, Play, Plus, ShieldCheck, SlidersHorizontal, UsersRound } from 'lucide-react';
import { Link } from 'wouter';
import { AppShell } from '@/components/app-shell';
import { JobModal } from '@/components/job-modal';
import { Button, EmptyState, Panel, ProgressBar, Skeleton, StatusPill } from '@/components/ui-primitives';
import { exportCsv, exportJson, useSandbox } from '@/hooks/use-sandbox';
import type { JobWithResults } from '@/lib/types';

function formatTime(value: string) {
  return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value));
}

function percent(job: JobWithResults) {
  return job.total ? Math.round((job.processed / job.total) * 100) : 0;
}

export default function Dashboard() {
  const { jobs, settings, hydrated, toggleJob, addJob } = useSandbox();
  const [showModal, setShowModal] = useState(false);
  const activeJob = useMemo(() => jobs.find((job) => job.status === 'running' || job.status === 'paused') ?? jobs[0], [jobs]);
  const totals = useMemo(() => jobs.reduce((acc, job) => ({ total: acc.total + job.total, processed: acc.processed + job.processed, found: acc.found + job.found, errors: acc.errors + job.errors }), { total: 0, processed: 0, found: 0, errors: 0 }), [jobs]);

  if (!hydrated) return <AppShell><div className="space-y-6"><Skeleton className="h-10 w-64" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-28" />)}</div><Skeleton className="h-80" /></div></AppShell>;

  return <AppShell>
    <div className="space-y-7 pb-20">
      <section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end animate-rise">
        <div><div className="mb-2 flex items-center gap-2 font-mono text-[10px] font-semibold uppercase tracking-[.18em] text-[hsl(var(--primary))]"><span className="h-1.5 w-1.5 rounded-full bg-[hsl(var(--primary))]" /> Current workspace</div><h1 className="font-display text-3xl font-semibold tracking-[-.04em] sm:text-[38px]">Keep the signal moving.</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">Prepare checking jobs, watch durable progress, and export only what you mean to share.</p></div>
        <Button onClick={() => setShowModal(true)} className="self-start sm:self-auto" data-testid="button-new-job"><Plus size={16} /> New checking job</Button>
      </section>

      <div className="flex items-start gap-3 rounded-md border border-[hsl(var(--accent)/.55)] bg-[hsl(var(--accent)/.13)] px-4 py-3.5 animate-rise animate-rise-delay-1" data-testid="banner-sandbox-notice"><ShieldCheck className="mt-0.5 shrink-0 text-[hsl(29_58%_31%)]" size={16} /><div className="text-xs leading-relaxed text-[hsl(29_45%_28%)]"><strong className="font-semibold">Sandbox mode.</strong> These are sample records for interface testing. No Telegram connection is active, and no phone number is sent anywhere.</div><Link href="/settings" className="ml-auto shrink-0 text-xs font-bold text-[hsl(29_58%_31%)] underline underline-offset-2" data-testid="link-configure-sandbox">Configure</Link></div>

      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 animate-rise animate-rise-delay-1">
        {[
          { label: 'Numbers in workspace', value: totals.total.toLocaleString(), detail: `${jobs.length} sample jobs`, icon: UsersRound, color: 'text-[hsl(var(--primary))]' },
          { label: 'Processed', value: totals.processed.toLocaleString(), detail: `${totals.total ? Math.round((totals.processed / totals.total) * 100) : 0}% of all numbers`, icon: Check, color: 'text-[hsl(var(--primary))]' },
          { label: 'Profiles found', value: totals.found.toLocaleString(), detail: `${totals.processed ? Math.round((totals.found / totals.processed) * 100) : 0}% of processed`, icon: ArrowUpRight, color: 'text-[hsl(var(--accent))]' },
          { label: 'Errors to review', value: totals.errors.toLocaleString(), detail: 'Across sample jobs', icon: CircleAlert, color: 'text-[hsl(var(--destructive))]' },
        ].map(({ label, value, detail, icon: Icon, color }) => <Panel key={label} className="group relative overflow-hidden p-4 transition-all hover:-translate-y-0.5 hover:shadow-[var(--shadow-sm)]"><div className="flex items-start justify-between"><span className="text-xs font-semibold text-[hsl(var(--muted-foreground))]">{label}</span><Icon size={16} className={color} /></div><div className="mt-4 font-display text-3xl font-semibold tracking-tight">{value}</div><div className="mt-1 font-mono text-[10px] uppercase tracking-wide text-[hsl(var(--muted-foreground))]">{detail}</div></Panel>)}
      </section>

      <section className="grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)] animate-rise animate-rise-delay-2">
        <Panel className="overflow-hidden">
          <div className="flex flex-col gap-3 border-b border-[hsl(var(--border))] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-display text-base font-semibold">Active run</h2>{activeJob && <StatusPill status={activeJob.status} />}</div><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{activeJob ? activeJob.name : 'No current job'}</p></div>{activeJob && <div className="flex items-center gap-2"><Button variant="outline" onClick={() => exportJson(activeJob)} data-testid="button-export-active-json"><FileJson size={14} /> JSON</Button><Button variant="outline" onClick={() => exportCsv(activeJob)} data-testid="button-export-active-csv"><FileSpreadsheet size={14} /> CSV</Button></div>}</div>
          {activeJob ? <div className="p-5"><div className="mb-2 flex items-end justify-between"><div><span className="font-mono text-4xl font-medium tracking-[-.08em] text-[hsl(var(--foreground))]">{percent(activeJob)}%</span><span className="ml-2 text-xs text-[hsl(var(--muted-foreground))]">complete</span></div><span className="font-mono text-xs text-[hsl(var(--muted-foreground))]">{activeJob.processed.toLocaleString()} / {activeJob.total.toLocaleString()}</span></div><ProgressBar value={percent(activeJob)} className="h-2" /><div className="mt-5 grid grid-cols-3 gap-3 border-t border-[hsl(var(--border))] pt-4"><div><div className="font-mono text-lg font-semibold">{activeJob.found}</div><div className="text-[11px] text-[hsl(var(--muted-foreground))]">Found</div></div><div><div className="font-mono text-lg font-semibold">{activeJob.notDiscoverable}</div><div className="text-[11px] text-[hsl(var(--muted-foreground))]">Private / absent</div></div><div><div className="font-mono text-lg font-semibold text-[hsl(var(--destructive))]">{activeJob.errors}</div><div className="text-[11px] text-[hsl(var(--muted-foreground))]">Errors</div></div></div><div className="mt-6 flex flex-col gap-3 rounded-md bg-[hsl(var(--muted)/.55)] px-3.5 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 text-xs text-[hsl(var(--muted-foreground))]"><Clock3 size={14} /> Updated {formatTime(activeJob.updatedAt)}<span className="text-[hsl(var(--border))]">/</span><span className="font-mono">{settings.minRequestInterval.toFixed(1)}s interval</span></div><Button variant={activeJob.status === 'running' ? 'outline' : 'primary'} onClick={() => toggleJob(activeJob.id)} data-testid={`button-${activeJob.status === 'running' ? 'pause' : 'resume'}-active-job`}>{activeJob.status === 'running' ? <><Pause size={14} /> Pause run</> : <><Play size={14} /> Resume run</>}</Button></div></div> : <EmptyState title="No active sample run" detail="Start a new local job to see durable progress here." action={<Button onClick={() => setShowModal(true)} data-testid="button-empty-new-job"><Plus size={14} /> Create job</Button>} />}
        </Panel>
        <Panel className="overflow-hidden"><div className="flex items-center justify-between border-b border-[hsl(var(--border))] px-5 py-4"><div><h2 className="font-display text-base font-semibold">Recent jobs</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">A compact run history</p></div><Link href="/jobs" className="text-[11px] font-bold text-[hsl(var(--primary))]" data-testid="link-view-all-jobs">View all</Link></div>{jobs.length ? <div className="divide-y divide-[hsl(var(--border))]">{jobs.slice(0, 4).map((job) => <Link href="/jobs" key={job.id} className="block px-5 py-3.5 transition-colors hover:bg-[hsl(var(--muted)/.45)]" data-testid={`link-recent-job-${job.id}`}><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-semibold">{job.name}</span><StatusPill status={job.status} /></div><div className="mt-2 flex items-center justify-between font-mono text-[10px] text-[hsl(var(--muted-foreground))]"><span>{job.processed.toLocaleString()} / {job.total.toLocaleString()}</span><span>{formatTime(job.updatedAt)}</span></div><ProgressBar value={percent(job)} className="mt-2 h-1" /></Link>)}</div> : <EmptyState title="No jobs yet" detail="Your prepared runs will appear here." />}</Panel>
      </section>
      <section className="grid gap-5 lg:grid-cols-[1fr_1fr] animate-rise animate-rise-delay-3"><Panel className="p-5"><div className="flex items-center gap-2"><SlidersHorizontal size={16} className="text-[hsl(var(--primary))]" /><h2 className="font-display text-base font-semibold">Run posture</h2></div><div className="mt-4 grid grid-cols-2 gap-5"><div><div className="font-mono text-xl font-semibold">{settings.maxAttempts}</div><div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Max attempts</div></div><div><div className="font-mono text-xl font-semibold">{settings.autoResume ? 'On' : 'Off'}</div><div className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Auto-resume</div></div></div><Link href="/settings" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-[hsl(var(--primary))]" data-testid="link-review-settings">Review safety settings <ArrowUpRight size={13} /></Link></Panel><Panel className="flex items-start gap-3 bg-[hsl(var(--sidebar))] p-5 text-[hsl(var(--sidebar-foreground))]"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-[hsl(var(--sidebar-primary)/.16)] text-[hsl(var(--sidebar-primary))]"><Download size={16} /></div><div><h2 className="font-display text-base font-semibold text-[hsl(var(--sidebar-accent-foreground))]">Export with intent</h2><p className="mt-1 text-xs leading-relaxed text-[hsl(var(--sidebar-foreground)/.62)]">Exports contain only the selected job and its observed result states. No session credentials or connection metadata are included.</p><Link href="/jobs" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[hsl(var(--sidebar-primary))]" data-testid="link-export-center">Open export center <ArrowUpRight size={13} /></Link></div></Panel></section>
    </div>
    {showModal && <JobModal onClose={() => setShowModal(false)} onCreate={(name, phones) => { addJob(name, phones); setShowModal(false); }} />}
  </AppShell>;
}