import { useMemo, useState } from 'react';
import { CalendarClock, FileJson, FileSpreadsheet, Filter, Pause, Play, Plus, Search, Trash2 } from 'lucide-react';
import { AppShell } from '@/components/app-shell';
import { JobModal } from '@/components/job-modal';
import { Button, EmptyState, Panel, ProgressBar, StatusPill, TextInput } from '@/components/ui-primitives';
import { exportCsv, exportJson, useSandbox } from '@/hooks/use-sandbox';
import type { JobWithResults, ResultStatus } from '@/lib/types';

function formatDate(value: string) {
  return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value));
}

function formatDateTime(value: string) {
  return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value));
}

function progress(job: JobWithResults) {
  return job.total ? Math.round(job.processed / job.total * 100) : 0;
}

export default function Jobs() {
  const { jobs, hydrated, toggleJob, addJob, deleteJob } = useSandbox();
  const [query, setQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [selectedId, setSelectedId] = useState('');
  const [showModal, setShowModal] = useState(false);
  const selected = useMemo(() => jobs.find((job) => job.id === selectedId) ?? jobs[0], [jobs, selectedId]);
  const filtered = useMemo(() => jobs.filter((job) => job.name.toLowerCase().includes(query.toLowerCase()) && (statusFilter === 'all' || job.status === statusFilter)), [jobs, query, statusFilter]);

  if (!hydrated) return <AppShell><div className="space-y-5"><div className="h-10 w-48 animate-pulse rounded bg-[hsl(var(--muted))]" /><div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><div className="h-[590px] animate-pulse rounded-lg bg-[hsl(var(--muted))]" /><div className="h-[590px] animate-pulse rounded-lg bg-[hsl(var(--muted))]" /></div></div></AppShell>;

  function removeSelected() {
    if (selected && window.confirm(`Delete "${selected.name}" from this browser?`)) {
      deleteJob(selected.id);
      setSelectedId('');
    }
  }

  return <AppShell>
    <div className="space-y-5 pb-20">
      <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end animate-rise"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-[hsl(var(--primary))]">Operations ledger</div><h1 className="mt-1 font-display text-3xl font-semibold tracking-[-.04em]">Checking jobs</h1><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">Inspect durable progress and decide what leaves the sandbox.</p></div><Button onClick={() => setShowModal(true)} data-testid="button-jobs-new"><Plus size={16} /> New checking job</Button></section>
      <div className="flex flex-col gap-3 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card)/.7)] p-3 sm:flex-row sm:items-center animate-rise animate-rise-delay-1"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[hsl(var(--muted-foreground))]" /><TextInput type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search job names" className="pl-9" data-testid="input-search-jobs" /></div><div className="flex items-center gap-2"><Filter size={14} className="text-[hsl(var(--muted-foreground))]" /><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="h-10 rounded-md border border-[hsl(var(--input))] bg-[hsl(var(--card))] px-3 text-sm outline-none focus:border-[hsl(var(--primary))]" data-testid="select-job-status"><option value="all">All statuses</option><option value="running">Running</option><option value="paused">Paused</option><option value="queued">Queued</option><option value="completed">Completed</option><option value="failed">Failed</option></select></div><span className="px-1 font-mono text-[10px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]" data-testid="text-job-count">{filtered.length} of {jobs.length}</span></div>
      <div className="grid gap-5 lg:grid-cols-[minmax(300px,.73fr)_minmax(0,1.27fr)] animate-rise animate-rise-delay-2">
        <Panel className="min-h-[570px] overflow-hidden"><div className="border-b border-[hsl(var(--border))] px-5 py-4"><h2 className="font-display text-base font-semibold">All jobs</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Local browser records only</p></div>{filtered.length ? <div className="divide-y divide-[hsl(var(--border))]">{filtered.map((job) => <button key={job.id} onClick={() => setSelectedId(job.id)} className={`block w-full px-5 py-4 text-left transition-colors hover:bg-[hsl(var(--muted)/.5)] ${selected?.id === job.id ? 'border-l-2 border-[hsl(var(--primary))] bg-[hsl(var(--primary)/.055)] pl-[18px]' : 'border-l-2 border-transparent'}`} data-testid={`button-select-job-${job.id}`}><div className="flex items-start justify-between gap-3"><span className="font-display text-sm font-semibold leading-snug">{job.name}</span><StatusPill status={job.status} /></div><div className="mt-3 flex items-center justify-between font-mono text-[10px] text-[hsl(var(--muted-foreground))]"><span>{job.processed.toLocaleString()} / {job.total.toLocaleString()}</span><span>{progress(job)}%</span></div><ProgressBar value={progress(job)} className="mt-2" /><div className="mt-3 flex items-center justify-between text-[11px] text-[hsl(var(--muted-foreground))]"><span className="flex items-center gap-1"><CalendarClock size={12} /> {formatDate(job.createdAt)}</span><span>{job.found} found</span></div></button>)}</div> : <EmptyState title="No matching jobs" detail={jobs.length ? 'Try a different name or status filter.' : 'Create a sample job to begin reviewing runs.'} action={!jobs.length ? <Button onClick={() => setShowModal(true)} data-testid="button-empty-jobs-new"><Plus size={14} /> Create job</Button> : undefined} />}</Panel>
        {selected ? <Panel className="overflow-hidden"><div className="border-b border-[hsl(var(--border))] px-5 py-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-lg font-semibold">{selected.name}</h2><StatusPill status={selected.status} /></div><p className="mt-1 font-mono text-[10px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">{selected.id} <span className="mx-1 text-[hsl(var(--border))]">/</span> Created {formatDate(selected.createdAt)}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => exportJson(selected)} data-testid="button-job-json"><FileJson size={14} /> JSON</Button><Button variant="outline" onClick={() => exportCsv(selected)} data-testid="button-job-csv"><FileSpreadsheet size={14} /> CSV</Button></div></div><div className="mt-5"><div className="mb-2 flex justify-between font-mono text-[11px]"><span className="text-[hsl(var(--muted-foreground))]">Durable progress</span><span>{selected.processed.toLocaleString()} / {selected.total.toLocaleString()}</span></div><ProgressBar value={progress(selected)} className="h-2" /></div></div>
          <div className="grid grid-cols-2 divide-x divide-y border-b border-[hsl(var(--border))] sm:grid-cols-4 sm:divide-y-0">{[['Processed', selected.processed], ['Found', selected.found], ['Not discoverable', selected.notDiscoverable], ['Errors', selected.errors]].map(([label, value]) => <div key={String(label)} className="px-4 py-3.5"><div className="font-mono text-xl font-semibold">{value}</div><div className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">{label}</div></div>)}</div>
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[hsl(var(--border))] bg-[hsl(var(--muted)/.38)] px-5 py-3"><div className="text-xs text-[hsl(var(--muted-foreground))]">Last updated {formatDateTime(selected.updatedAt)}</div><div className="flex items-center gap-2">{(selected.status === 'running' || selected.status === 'paused') && <Button variant="outline" onClick={() => toggleJob(selected.id)} data-testid={`button-toggle-job-${selected.id}`}>{selected.status === 'running' ? <><Pause size={14} /> Pause</> : <><Play size={14} /> Resume</>}</Button>}<Button variant="quiet" className="text-[hsl(var(--destructive))] hover:text-[hsl(var(--destructive))]" onClick={removeSelected} data-testid="button-delete-job"><Trash2 size={14} /> Delete</Button></div></div>
          <div className="p-5"><div className="mb-3 flex items-center justify-between"><div><h3 className="font-display text-sm font-semibold">Observed results</h3><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Privacy-aware result states; absent data is intentional.</p></div><span className="font-mono text-[10px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">{selected.results.length} preview rows</span></div>{selected.results.length ? <div className="overflow-x-auto rounded-md border border-[hsl(var(--border))]"><table className="w-full min-w-[670px] text-left"><thead className="bg-[hsl(var(--muted)/.65)]"><tr className="font-mono text-[9px] uppercase tracking-[.14em] text-[hsl(var(--muted-foreground))]"><th className="px-3 py-2.5 font-medium">Phone</th><th className="px-3 py-2.5 font-medium">Result</th><th className="px-3 py-2.5 font-medium">Identity</th><th className="px-3 py-2.5 font-medium">Last online</th></tr></thead><tbody className="divide-y divide-[hsl(var(--border))]">{selected.results.map((result, index) => <tr key={`${result.phone}-${index}`} className="text-xs hover:bg-[hsl(var(--muted)/.35)]" data-testid={`row-result-${selected.id}-${index}`}><td className="whitespace-nowrap px-3 py-3 font-mono text-[11px]">{result.phone}</td><td className="px-3 py-3"><StatusPill status={result.status as ResultStatus} /></td><td className="px-3 py-3">{result.status === 'found' ? <div><div className="font-semibold">{result.displayName}</div><div className="mt-0.5 font-mono text-[10px] text-[hsl(var(--muted-foreground))]">@{result.username} / ID {result.telegramId}</div></div> : <span className="text-[hsl(var(--muted-foreground))]">{result.status === 'not_discoverable' ? 'No public identity returned' : 'No identity available'}</span>}</td><td className="whitespace-nowrap px-3 py-3 text-[hsl(var(--muted-foreground))]">{result.lastOnline ? formatDateTime(result.lastOnline) : '—'}</td></tr>)}</tbody></table></div> : <EmptyState title="No result preview" detail="This job has no observed rows yet. Export will still include the job envelope." />}</div>
        </Panel> : <Panel><EmptyState title="No job selected" detail="Select a job from the ledger to inspect its run." /></Panel>}
      </div>
    </div>
    {showModal && <JobModal onClose={() => setShowModal(false)} onCreate={(name, phones) => { const job = addJob(name, phones); setSelectedId(job.id); setShowModal(false); }} />}
  </AppShell>;
}